#!/bin/bash
# Most of the code is explainable on it's own

BLUE="\033[1;34m"
NOCOLOR="\033[0m"

echo

echo -e "${BLUE}Update Arch Linux Packages${NOCOLOR}"
sudo pacman -Syu

echo 

# Since yay is the more popular option, this is the one which is uncommented.

echo -e "${BLUE}Update AUR Packages${NOCOLOR}"
yay -Syu
# paru -Sau

echo 

# Not everyone uses Flatpak, hence why I commented the commands. You can uncomment these commands if you also wanna upgrade your flatpak packages.

# echo -e "${BLUE}Update Flatpak Packages${NOCOLOR}"
# flatpak update

# echo

# Personally I do not use snap, but if you want to update your snap packages with the script you can uncomment these commands.

# echo -e "${BLUE}Update Snap Packages¼{NOCOLOR}"
# sudo snap refresh

# echo
